### ISSUE TITLE
Generic Plugin

### ISSUE THREAD

**Issue by jsavko** [redloro/smartthings#3]
Thanks for putting this together and publishing it. Working with Smartthings on a local network can be a pain with the IP/MAC address issues.  

Is there any chance you can provide a template for a generic device?  I don't have any of the devices you have listed, but I do have some ESP8266's I'd love to be able to interface into smartthings. 

Thanks!

**Comment by redloro** [comment]
Hey - just added a sample plugin, smartapp and devicetype called Generic.  You can use this to test and see how the system works.

**Comment by jsavko** [comment]
Thanks!
