### ISSUE TITLE
"npm install" fails on Raspberry Pi 3 - appears to be the pcap dependency

### ISSUE THREAD

**Issue by twangus** [redloro/smartthings#7]
The recently added pcap dependency breaks "npm install" for me on the Raspberry Pi 3.  This is on a completely clean install of the latest Raspbian, following the steps in your video to install node v6.10.2.

If I remove the pcap dependency from packages.json, then npm install works for me and everything seems to work.

It looks like it is an issue with the "socketwatcher" package that pcap depends on.

Any ideas?

[npm-install-error.txt](https://github.com/redloro/smartthings/files/949299/npm-install-error.txt)

**Comment by redloro** [comment]
Yup... you only need pcap if you are installing the dash.js plugin... refer to the first thread -> FAQ -> What do I need to do to get this running? -> Step 12: https://community.smartthings.com/t/release-amazon-dash-button/85019

If you want to install the dash.js plugin you need to run:
```
sudo apt-get install libpcap-dev
```
and then you can run npm install.  If you don't want the dash.js plugin, just remove line 9 (pcap) from package.json.
